language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0


matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit
  - php -n vendor/bin/athletic -p test/Performance

after_script:


notifications:
  email: m.razvan92@gmail.com

sudo: false